### PR TITLE
onlyoffice filename corrupted after editing

### LINKED ISSUE #683: OnlyOffice: filename corrupted after editing
**Describe the bug**
Create a new Untitled.docx file. Download it, it's fine, downloads as expected. Edit the file in OnlyOffice, close it, wait 15 seconds for OnlyOffice to save, then download the file. Now it downloads as `output.docxmd5dzKxBsDeZxFG2m_cJCZDAgexpires1728494735WOPISrc202410091709413Dtdrive_onlyoffice3D3D-6s04n6wEe-YVDVRKFL0yWuXTeCBZhHvtG1PzkZFPtGR2SzkRglLM7-ghTCsWcQVfilenameoutput.docx`.

```
twake-cli editing_session list -a
Platform configuration:
	     : 󰩠 "mongodb://localhost:27017"  "tdrive"
	󰉙 local:  "/tmp/td"
	󰥖     :  "Same mongodb as database"
	󰶉 local
editing_session list > ✔ Platform: started


DriveFiles:

- Untitled.docx (f6ede00c-4a8e-4a6b-b7d2-3cdab81a2a6a) of a@b.c
  - modified: 2024-10-09T17:10:34.560Z
  - Versions:
    - 2024-10-09T17:09:36.825Z by a@b.c
        - id:          cf1eba81-efa9-4dfc-be8f-4a0b09f045e8
        - filename:    Untitled.docx
        - meta.name:   Untitled.docx
        - size:        10230 (+10230)
        - application: ""
    - 2024-10-09T17:10:34.560Z by a@b.c
        - id:          ae9f955f-c6ac-4f58-bafc-2f1f4a5bb221
        - filename:    
        - meta.name:   output.docx?md5=dzKxBsDeZxFG2m_cJCZDAg&expires=1728494735&WOPISrc=20241009170941%3Dtdrive_onlyoffice%3D%3D-6s04n6wEe-YVDVRKFL0yWuXTeCBZhHvtG1PzkZFPtGR2SzkRglLM7-ghTCsWcQV&filename=output.docx
        - size:        26403 (+16173)
        - application: "tdrive_onlyoffice"
```

Download request
image

Raw: `attachment; filename="output.docxmd5dzKxBsDeZxFG2m_cJCZDAgexpires1728494735WOPISrc202410091709413Dtdrive_onlyoffice3D3D-6s04n6wEe-YVDVRKFL0yWuXTeCBZhHvtG1PzkZFPtGR2SzkRglLM7-ghTCsWcQVfilenameoutput.docx"; filename*=UTF-8''output.docxmd5dzKxBsDeZxFG2m_cJCZDAgexpires1728494735WOPISrc202410091709413Dtdrive_onlyoffice3D3D-6s04n6wEe-YVDVRKFL0yWuXTeCBZhHvtG1PzkZFPtGR2SzkRglLM7-ghTCsWcQVfilenameoutput.docx`

Title in OO is different than in drive:
image

### PR DESCRIPTION
**Pull request by ericlinagora**
Fix #683 

Filename handling is going to be worth a major refactor

### CODE REVIEW

File: tdrive/backend/node/src/services/documents/web/controllers/documents.ts [hunk 1]
```diff
@@ -422,7 +422,7 @@ export class DocumentsController {
         totalChunks: parseInt(q.resumableTotalChunks || q.total_chunks) || 1,
         totalSize: parseInt(q.resumableTotalSize || q.total_size) || 0,
         chunkNumber: parseInt(q.resumableChunkNumber || q.chunk_number) || 1,
-        filename: q.resumableFilename || q.filename || file?.filename || undefined,
```
Comment (shepilov) [inline tdrive/backend/node/src/services/documents/web/controllers/documents.ts:425]: are you sure you don't get a filename from "resumableFilename" when you upload a file with resumable.js?

Comment (shepilov) [reply tdrive/backend/node/src/services/documents/web/controllers/documents.ts:425]: and how it's connected with OO?

Comment (ericlinagora) [reply tdrive/backend/node/src/services/documents/web/controllers/documents.ts:425]: > are you sure you don't get a filename from "resumableFilename" when you upload a file with resumable.js?

I'm not sure it doesn't, but it doesn't seem necessary. I tested a multi chunk upload and download, worked fine.

> and how it's connected with OO?

this is ultimately called by the OO callback when it ends an editing session

**Review by shepilov — APPROVED** [review]
